we're progressing.
 NameError: name 'os' is not defined. Did you forget to import 'os'?

YES I DID. BECAUSE I HAVE TO CHANGE THIS GODDAMN LINE FOR THE 8TH FUCKING TIME